const { Model, DataTypes } = require("sequelize");

class Produtor extends Model {
  static init(sequelize) {
    super.init(
      {
        nome_fantasia: DataTypes.STRING,
        registro: DataTypes.STRING,
        razao_social: DataTypes.STRING,
        pais: DataTypes.STRING,
        uf: DataTypes.STRING,
        cidade: DataTypes.STRING,
        cep: DataTypes.STRING,
        endereco: DataTypes.STRING,
        atividade: DataTypes.STRING,
        nome_1: DataTypes.STRING,
        cargo_1: DataTypes.STRING,
        data_aniversario_1: DataTypes.STRING,
        telefone_1: DataTypes.STRING,
        celuar_1: DataTypes.STRING,
        whatsapp_1: DataTypes.STRING,
        email_1: DataTypes.STRING,
        redes_sociais_1: DataTypes.STRING,
        nome_2: DataTypes.STRING,
        cargo_2: DataTypes.STRING,
        data_aniversario_2: DataTypes.STRING,
        telefone_2: DataTypes.STRING,
        celuar_2: DataTypes.STRING,
        whatsapp_2: DataTypes.STRING,
        email_2: DataTypes.STRING,
        redes_sociais_2: DataTypes.STRING,
        datas_contato: DataTypes.STRING,
        nome_3: DataTypes.STRING,
        cargo_3: DataTypes.STRING,
        data_aniversario_3: DataTypes.STRING,
        telefone_3: DataTypes.STRING,
        celuar_3: DataTypes.STRING,
        whatsapp_3: DataTypes.STRING,
        email_3: DataTypes.STRING,
        redes_sociais_3: DataTypes.STRING,
        nome_4: DataTypes.STRING,
        cargo_4: DataTypes.STRING,
        data_aniversario_4: DataTypes.STRING,
        telefone_4: DataTypes.STRING,
        celuar_4: DataTypes.STRING,
        whatsapp_4: DataTypes.STRING,
        email_4: DataTypes.STRING,
        redes_sociais_4: DataTypes.STRING,
        site: DataTypes.STRING,
        status: DataTypes.STRING,
        registros: DataTypes.STRING,
        cultivares: DataTypes.STRING,
        outro_cultivo: DataTypes.STRING,
        metodo_cultivo: DataTypes.STRING,
        outro_metodo: DataTypes.STRING,
        area_fisica_total: DataTypes.STRING,
        area_hidroponica: DataTypes.STRING,
        vol_producao_total: DataTypes.STRING,
        localizacao: DataTypes.STRING,
        outro_cultivo_paralelo: DataTypes.STRING,
        migrou_para_hidroponia: DataTypes.STRING,
        profissao_anterior: DataTypes.STRING,
        movimentacao_financeira: DataTypes.STRING,
        data_hora: DataTypes.DATE,
      },
      {
        sequelize,
        tableName: "produtores",
      }
    );
  }
}

module.exports = Produtor;
